import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

abstract final class AppTheme {
  static ThemeData light = FlexThemeData.light(
    scheme: FlexScheme.shadBlue,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      useM2StyleDividerInM3: true,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonSelectedForegroundSchemeColor: SchemeColor.onPrimary,
      segmentedButtonUnselectedSchemeColor: SchemeColor.onPrimary,
      segmentedButtonRadius: 8.0,
      segmentedButtonBorderWidth: 0.5,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorSchemeColor: SchemeColor.onPrimary,
      inputCursorSchemeColor: SchemeColor.primary,
      inputSelectionHandleSchemeColor: SchemeColor.primary,
      inputDecoratorBorderSchemeColor: SchemeColor.primary,
      scaffoldBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
      inputDecoratorIsFilled: true,
      inputDecoratorBorderWidth: 0.5,
      inputDecoratorRadius: 8.0,
      fabUseShape: true,
      fabAlwaysCircular: true,
      alignedDropdown: true,
      appBarBackgroundSchemeColor: SchemeColor.primaryContainer,
      navigationRailUseIndicator: true,
      elevatedButtonElevation: 0.0,
      elevatedButtonRadius: 8.0,
      filledButtonRadius: 8.0,
      cardRadius: 8.0,
      cardElevation: 0.0,
      cardBackgroundSchemeColor: SchemeColor.onPrimary,
      cardBorderSchemeColor: SchemeColor.surfaceContainerHighest,
      cardBorderWidth: 0.5,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
  );

  static ThemeData dark = FlexThemeData.dark(
    scheme: FlexScheme.shadBlue,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      useM2StyleDividerInM3: true,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonSelectedForegroundSchemeColor: SchemeColor.onPrimary,
      segmentedButtonUnselectedSchemeColor: SchemeColor.onPrimary,
      segmentedButtonRadius: 8.0,
      segmentedButtonBorderWidth: 0.5,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorSchemeColor: SchemeColor.onPrimary,
      inputCursorSchemeColor: SchemeColor.primary,
      inputSelectionHandleSchemeColor: SchemeColor.primary,
      inputDecoratorBorderSchemeColor: SchemeColor.primary,
      scaffoldBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
      inputDecoratorIsFilled: true,
      inputDecoratorBorderWidth: 0.5,
      inputDecoratorRadius: 8.0,
      fabUseShape: true,
      fabAlwaysCircular: true,
      alignedDropdown: true,
      appBarBackgroundSchemeColor: SchemeColor.primaryContainer,
      navigationRailUseIndicator: true,
      elevatedButtonElevation: 0.0,
      elevatedButtonRadius: 8.0,
      filledButtonRadius: 8.0,
      cardRadius: 8.0,
      cardElevation: 0.0,
      cardBackgroundSchemeColor: SchemeColor.onPrimary,
      cardBorderSchemeColor: SchemeColor.surfaceContainerHighest,
      cardBorderWidth: 0.5,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
  );
}
